### ISSUE TITLE
Bug: Serialization of integers exceeding int64 is not supported

### ISSUE THREAD

**Issue by harochau** [litestar-org/litestar#1544]
### Summary

when I try in v2.0.0alpha4
```
@get("/")
async def hello_world() -> dict:
    bad_dict = {"value": 1000000000000000000000000000000000000000000000000}
    return bad_dict
```
    
`
OverflowError: can't serialize ints < -2**63 or > 2**64 - 1
`

I managed to find a temporary workaround
```
from fastapi.encoders import jsonable_encoder
...
return jsonable_encoder(bad_dict, custom_encoder={int: lambda x: str(x)})
```
I think it should be really prominent in the docs (parts like "Migrating to Litestar") that you can't trust arbitrary python dicts and you can't just 
`
return httpx.get(..).json()
`
in your endpoints because Litestar uses untraditional serializer for json

**Comment by provinzkraut** [comment]
I have raised an issue (https://github.com/jcrist/msgspec/issues/377) in the msgspec repo requesting a general way to work around this limitation. If this cannot be resolved, we should come up with something ourselves or at least mention this in the documentation.

Re-labeling this as a bug for now.

**Comment by provinzkraut** [comment]
@harochau This issue has been somewhat mitigated on msgspec's side. I'd advise you though to read https://github.com/jcrist/msgspec/issues/377#issuecomment-1513253768, where @jcrist provides some good insights.

> I think it should be really prominent in the docs (parts like "Migrating to Litestar") that you can't trust arbitrary python dicts and you can't just
`return httpx.get(..).json()`
in your endpoints because Litestar uses untraditional serializer for json

I would not go so far as to say you can't trust Litestar with arbitrary dicts or that it uses an untraditional serialiser. The fact is that most implementations simply don't properly support serialization of such values and Litestar happened to chose a library that's explicit about this.

For Python's `json.dumps` encodes `2 ** 64` as `18446744073709551616`, while JavaScript's `JSON.stringify` will encode it as `18446744073709552000`. If you need accuracy in these ranges, you should generally just chose a different representation that's guaranteed to be consistent across different platforms.

**Comment by harochau** [comment]
Thanks for everybody involved in this chain, the speed was impressive!

With manually installing 
`
poetry add git+https://github.com/jcrist/msgspec@792226c6c38ced5c3e2b129458bc033316bbab2d 
`
everything works as expected now

**Comment by jcrist** [comment]
msgspec 0.14.2 has now been released, containing support for encoding integers outside the 64 bit range. I believe this issue can be closed.

**Comment by peterschutt** [comment]
Thanks @jcrist!
