### ISSUE TITLE
Enhancement: Implement DTOConfig.include

### ISSUE THREAD

**Issue by MatthewNewland** [litestar-org/litestar#1588]
### Description

The `DTOConfig` `include` field (which is mentioned in the documentation for the `exclude` field) is missing in litestar 2.0.0.alpha5. (It was present on the `main` branch recently.)

### URL to code causing the issue

https://github.com/litestar-org/litestar/blob/3b5da84509b85cfeccc9dce495369b2b299f6d52/litestar/dto/factory/config.py#L17

### MCVE

```python
class User(Base):
    name: Mapped[str]
    password: Mapped[str]

UserReadDTO = SQLAlchemyDTO[Annotated[User, DTOConfig(include={"name"})]]
```

### Litestar Version

2.0.0.alpha5

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

<a href="https://polar.sh/litestar-org/litestar/issues/1588">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1588/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1588/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
This is intentional. @peterschutt can shed light on this as required.

**Comment by provinzkraut** [comment]
This is mentioned as a breaking in the [release notes](https://docs.litestar.dev/2/release-notes/changelog.html#2.0.0alpha5-misc) for `2.0.0alpha5`. This is the relevant PR with some more details: #1580.

**Comment by MatthewNewland** [comment]
Fair enough, but the docstring is still misleading.

**Comment by provinzkraut** [comment]
> the docstring is still misleading.

Which docstring?

**Comment by peterschutt** [comment]
Hey @MatthewNewland - I did rip this out for a5, along with some other config options that I felt needed more thought. It will go back in as it's useful.

I want to get `exclude` feature complete first (basically this is support for nested excludes, e.g `exclude={"a", "b.c"}`).

Previously `include` would throw an error if specified with `exclude`, but I don't know if that is what we want, as it might be nice to be able to do `exclude={"a"}, include={"b.c"}`. So, I ripped it out in order to have this conversation.

Good to know you are/were using the feature, as I'll prioritise accordingly. Maybe ripping it out was a bit knee jerk, as with the exception if both `include` and `exclude` are specified, any relaxation can't be breaking.
