### ISSUE TITLE
Docs: how to add multiple auth middlewares?

### ISSUE THREAD

**Issue by robertlagrant** [litestar-org/litestar#1940]
### Summary

I'd love some documentation on how to chain together authentication middlewares until either one succeeds, and performs the request, or they all fail and the API returns a 401.

My use case is is I'd like to use the JWT middleware to authenticate some requests, that come from users, from a bearer token, but then also a custom middleware to authenticate API requests from an X-API-Key header. I don't want API calls to 401 because the JWT middleware fails.

I don't know if this is possible through configuration, or if I'd need to make an overarching middleware that somehow calls the others in tandem, but I couldn't find any documentation on how to achieve this. Apologies if it exists and I missed it.

**Comment by robertlagrant** [comment]
Thank you, and for the lightning fast response. I'm happy to help contribute a generic recipe if I can get a pointer on how to programmatically call the middlewares.

**Comment by provinzkraut** [comment]
Middlewares already call other middlewares / ASGI apps, since they themselves are ASGI apps as well.

It usually looks something like 

```python
await self.app(scope, send, receive)
```

So if you were to wrap one middleware into another, you'd simply wrap these calls. 

You can take a look at https://github.com/litestar-org/litestar/blob/a288fd49ec50426da146f8e9071163d5b892c335/litestar/middleware/base.py or the middlewares in https://github.com/litestar-org/litestar/tree/a288fd49ec50426da146f8e9071163d5b892c335/litestar/middleware to see how that's usually implemented.
