### ISSUE TITLE
Enhancement: integration with external OAuth2 provider.

### ISSUE THREAD

**Issue by cofin** [litestar-org/litestar#2071]
### Summary

It would be great to have an integration with a third party library or have built in support for authenticating with OAuth2 providers such as Google or Github.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2071">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2071/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2071/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
This could/would be accomplished by developing an internal plugin via https://docs.litestar.dev/latest/usage/plugins.html#plugins.

Some examples of others: 
- https://github.com/litestar-org/litestar/pull/3145#issuecomment-1966921258
- https://github.com/cofin/litestar-granian
- https://github.com/guacs/litestar-svcs

**Comment by codespearhead** [comment]
By "external OAuth2 provider", do you mean a Python library or a separate OAuth2 provider? Because [Keycloak](https://github.com/keycloak/keycloak) is a no-brainer despite being written in Java.

There's also [python-social-auth](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/github.py), which is used by [Zulip](https://github.com/zulip/zulip/blob/22bd8048b118f93758d2b0afd76acfc89eeeb3d9/zproject/backends.py#L2072) and [Sentry](https://github.com/getsentry/sentry/blob/f30cabd30a08718e26bee96a25e75e2b4ecc8b23/src/social_auth/backends/github.py#L35).

However, it's worth noting that both projects seem to have integrated that library's source code into their own repository. Hence, their "forks" are maintained independently, which impacts [the library's health and integrity](https://github.com/python-social-auth/social-core/issues/445).

**Comment by JacobCoffee** [comment]
I think at this stage, we have "native" support in the library and all we need to do OAuth2 connections as a client to any server.

I'm not sure what we want here, but maybe some nice abstraction with some built-in common providers as a plugin that users can opt-in to?

@litestar-org/maintainers

**Comment by codespearhead** [comment]
Makes Sense, just like [Laravel Socialite](https://github.com/laravel/socialite) provides an OAuth client with a few official adapters, whereas other adapters are [maintained by the community](https://github.com/SocialiteProviders/Providers/tree/master/src).

**Comment by cofin** [comment]
This has been completed.  There's now a working sample on the litestar-fullstack-inertia repository.  Additionally, I've created a PR with the maintainer of `httpx-oauth` for integrated support.
