### ISSUE TITLE
Bug: using Any return type on before_request handler throws an error on schema

### ISSUE THREAD

**Issue by rseeley** [litestar-org/litestar#2368]
### Description

Using `Any` as a return type for a `before_request` handler throws an error when accessing the schema pages/openapi.json endpoints. Looking at the documentation, it should return some value or `None`, and using one or both of those as a return type is successful. The API itself runs just fine with an invalid return type, and this only seems to affect the schema routes.

It seems like maybe this is expected behavior so that you are forced to set a proper return type, but maybe a more extensive error message pointing to the location of the issue could be added? The current error I get is `litestar.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Unable to serialize response content`, which took a while to figure out what caused it.

### URL to code causing the issue

https://github.com/rseeley/litestar-before-request-error-mvce/blob/main/app.py

### Steps to reproduce

```bash
1. Follow the steps in the README section titled "Install litestar"
2. Access the schema at http://127.0.0.1:8000/schema or http://127.0.0.1:8000/schema/openapi.json
```

### Litestar Version

2.1.1

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2368">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2368/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2368/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Thanks for the great MCVE!

What's happening here is Litestar alters the return type of the handler based on the return type of the hook if it's not `None` or ` | None`. Since the hook returns an `ASGIResponse` if you don't return anything, and we default to encode with JSON, Litestar will then attempt to encode the `ASGIResponse` as JSON.

I'm not entirely sure *why* we alter the return type like this, @peterschutt do you have any insight there? I removed the code in question and it didn't seem to break anything, so I'm not even sure this is actually intentional.

In any case, I don't think we *should* be doing this, since it's extremely unexpected and I can't think of a good reason why this would be the desired behaviour. The return type of the handler should be the source of truth in any case, and it's the user's responsibility to return an appropriate type from any hooks that might be in the pipeline.
