### ISSUE TITLE
Enhancement: Infer Jinja files as text/html

### ISSUE THREAD

**Issue by ADV1K** [litestar-org/litestar#2449]
### Summary

The `media_type` is not inferred correctly when rendering a Jinja template with file extensions other than `.html` such as `.jinja`, `.jinja2`, `.j2`.

So instead of passing a `media_type` explicitly, like so `Template("App.jinja", media_type="text/html")`, it would be nice if litestar infers the type.

### Basic Example

```python
@get("/")
async def home() -> Template:
    return Template("App.jinja")  # notice the file extension
```

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2449">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2449/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2449/pledge.svg">
</picture>
</a>

**Comment by marcuslimdw** [comment]
A template response's media type is set at `litestar/response/template.py:129` (as of 2.3.2). I started work on this, but am not sure about the proper design:

Different template engines may have different inference rules, and Litestar should be decoupled from them. This logic should therefore not exist in `Template`. 

Logically, therefore, it should be placed in `TemplateEngineProtocol` implementations (note: `Protocol` [doesn't support optional members](https://peps.python.org/pep-0544/#support-optional-protocol-members)). At the same time, however, to maintain backwards compatibility, `Template` should fall back to the current implementation, suggesting an algorithm something like this:
  1. Check if `infer_media_type` exists on `template_engine`
  2. If it doesn't, use the existing algorithm
  3. If it does, call `infer_media_type`
  4. If `infer_media_type` returns a `str` or `MediaType`, use that; otherwise, use the existing algorithm

The reason the existing algorithm doesn't infer a media type for `jinja2` templates is that it just uses `mimetype` (from the stdlib).

Furthermore, Jinja2 (and presumably other templating frameworks) can be used for non-HTML content (XML comes to mind), which means that this may not be a desirable change:

* It would decentralise media type inference logic between `mimetype` and template engines
* Rather than refusing the temptation to guess, we would be optimising the dominant case at the expense of the edge cases

Overall, I do like this because I personally don't suffix my templates with `.html`, and so it would benefit me, but I feel like having a maintainer weigh in on the intended direction of the project would be useful.

**Comment by provinzkraut** [comment]
> is not inferred correctly when rendering a Jinja template with file extensions other than `.html`

The inferrence is actually correct. Jinja is a text based templating engine, not HTML. You can render any sort of text document with it, so the `.jinja`-extension doesn't realiably tell you anything about the 

> Furthermore, Jinja2 (and presumably other templating frameworks) can be used for non-HTML content (XML comes to mind), which means that this may not be a desirable change

This is a very important aspect. A `.jinja` extension doesn't necessarily guarantee HTML, and serving files with that extension as `text/html` would definitely be a breaking change.

In general, I think we shouldn't make this too complex; the behaviour of inferring the media type from the extension and having to supply it explicitly if that's not possible is reasonable and works well enough for most use cases.


<hr>

As a workaround (which is what I tend to do as well), you could just suffix your files as `.jinja.html`. This works well with most editors and the media type will be inferred correctly.

**Comment by euri10** [comment]
please note also that when using another file extension than html to write html you may want to be sure of your autoescape settings, using an html extension and Litestar default jinja config provides you with that safety net.

**Comment by provinzkraut** [comment]
I'm going to close this as there's no action to be performed here. @ADV1K feel free to re-open if you have any more questions-
