### ISSUE TITLE
Bug: openapi schema generation fails for Union of/in msgspec.Struct models

### ISSUE THREAD

**Issue by aedify-swi** [litestar-org/litestar#2971]
### Description

Hello!

In the latest versions(s) (I think this originates from the changes regarding nested models in openapi generation) we cannot use Unions of `msgspec.Struct`s anymore. Neither as direct return types for routes nor nested within return types. 

The result is a 500 Error. The MCVE below raises `'types.UnionType' object has no attribute '__qualname__'` internally. In our production app I get `typing.Union is not a module, class, method, or function.` instead.

Cheers

### MCVE

```python
import msgspec
import uvicorn
from litestar import Litestar, get


class SubStructA(msgspec.Struct):
    a: int


class SubStructB(msgspec.Struct):
    a: int


class StructyStruct(msgspec.Struct):
    sub: SubStructA | SubStructB


@get("/subunion")
async def testSubUnion() -> StructyStruct:
    return StructyStruct(SubStructA(0))


@get("/union")
async def testUnion() -> SubStructA | SubStructB:
    return SubStructA(0)


app = Litestar(route_handlers=[test2]) # or test
uvicorn.run(app)
```

### Steps to reproduce

```bash
Run the example and browse to `localhost:8000/schema`
```

### Litestar Version

2.5.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2971">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2971/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2971/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Thanks for report @aedify-swi, confirmed.

Guessing that you are using 3.8 or 3.9 in prod app with `Union` instead of  ` | `?

Issue is with our internal schema generation plugin for `Struct` types.

https://github.com/litestar-org/litestar/blob/cc45c1132584210250dd725595612c9c95c4bf68/litestar/_openapi/schema_generation/plugins/struct.py#L21-L22

`FieldDefinition.is_subclass_of()` will return `True` if all elements of the union are subclasses of `Struct`, however the plugin doesn't make any effort to handle unions, nor should it b/c the schema generation scaffolding above it manages that. So if it receives a union, irrespective of the member types, it should return `False`.

Changing that to:

```py
    def is_plugin_supported_field(self, field_definition: FieldDefinition) -> bool:
        return not field_definition.is_union and field_definition.is_subclass_of(Struct)
```

seems to sort it:

![image](https://github.com/litestar-org/litestar/assets/20659309/2f4028c9-2bc2-48e8-ab6f-7925fde07957)

**Comment by peterschutt** [comment]
> Nope. 3.12

Any chance you can provide a traceback for your prod issue please?
