### ISSUE TITLE
Bug: Logger memory leak through threads

### ISSUE THREAD

**Issue by 0xSwego** [litestar-org/litestar#3080]
### Description

I discovered that each time a logger is created, a new thread is spawned and never cleaned up.

I create loggers during the execution of API calls, as I want the arguments to persist in all log entries. This causes the creation of a huge number of threads, that, after some time, make the application crash.

![image](https://github.com/litestar-org/litestar/assets/21270278/18830d64-29a0-4aaa-882c-43701d0285e6)

### MCVE

```py
# Fetching the active threads
import threading
dangling_threads = [thread.name for thread in threading.enumerate() if thread.is_alive()]
```

```py
# This creates a new thread that will never be cleaned up!
logger = log.get_logger()
```

### Litestar Version

2.5.3

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3080">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3080/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3080/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
Heya, can you tell what is `log` in `log.get_logger()`? It would be more beneficial if you can give some more code that preferably shows your logging config as well. I could not (maybe others could) make much from your MCVE.

**Comment by provinzkraut** [comment]
This is expected behaviour and not an issue with Litestar. 

> I create loggers during the execution of API calls

You should not create a new logger for each API call. If you need a specific logger for these calls, you should create one logger for this which is then reused.

The threads being created is simply how the [`QueueListener`](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.QueueListener) along with the [`QueueHandler`](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.QueueHandler) work.
You're likely not cleaning up the loggers properly (i.e. calling [`.stop()`](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.QueueListener.stop), which stops the thread), causing them to go on indefinitely.

If you share an MCVE with this, we can maybe help you come up with a different solution for your logging needs.

**Comment by 0xSwego** [comment]
> This is expected behaviour and not an issue with Litestar.

Quite shocked about it. 

I understand the necessity of offloading such operations to a separate thread, but it feels counterintuitive to me to spawn a new thread each time a new logger is created. I guess it is a necessary artifact of the huge logging framework python relies on.

No need for help then, I've refactored my code to just use 1 single global logger. Thanks!
