### ISSUE TITLE
Bug: New `create_static_files_router` automatically adds routes to schema docs

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#3374]
### Description

I found this suprising when using the new static files feature that
1: It auto adds these to the schema
2: It adds them under a sort've "ugly" router header `default`

We should fix one or both of those

### MCVE

```python
from litestar import Litestar
from litestar.static_files import create_static_files_router

app = Litestar(
    route_handlers=[
        create_static_files_router(directories=["assets"], path="/static"),
    ],
)
```

### Steps to reproduce

```bash
1. run mcve
2. visit /schema
3. See schema for default
```

### Screenshots
<img width="508" alt="image" src="https://github.com/litestar-org/litestar/assets/45884264/a6145e1a-370f-4105-bfec-cf73bddc90cd">

### Litestar Version

2.7/2.8

### Platform

- [X] Linux
- [X] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

**Comment by provinzkraut** [comment]
Why wouldn't it add them to the schema? It's just regular route handlers, which, by default, are added to the schema. You can use the regular `include_in_schema=False` if you don't want them included.

Not sure about the name; We do include a `name` param which defaults to `static`. No idea where the `default` comes from, that might be a bug.

**Comment by JacobCoffee** [comment]
We didn't include them before, but I feel like - by default - they should be disabled. 
The `default` is a tagless section iirc.

I'm fine with whatever here, but at the very least I hope we would tag this as something more not-`default`-ey

**Comment by peterschutt** [comment]
> The `default` is a tagless section iirc.

If you pass `tags=["static"]` (or whatever you want to call it) to the `create_static_files_router()` function, does that replace the "default" section? Maybe we should have a default that is not `None` for that?

**Comment by Nozavi** [comment]
I, for one, chose to stick with StaticFilesConfig as much as possible just because it does NOT add the routes to the schema docs. Since I'll never use them, I'd rather not see/have them there. So, for what it's worth, I'd also classify this as a bug (especially if you take into consideration that create_static_files_router is presented as the replacement for StaticFilesConfig, but it does not replace/mimic its behavior exactly).

**Comment by peterschutt** [comment]
FWIW, I think `include_in_schema=False` is a sane default for the static files router.

**Comment by Nozavi** [comment]
I checked again just now and realized there was one additional reason/inconsistency: after switching to create_static_files_router (using the exact same settings: directories=["static"], path="/static") I immediately noticed my favicon was 404ing all of a sudden because its URL was now **/schema/static/favicon.ico** instead of StaticFilesConfig's **/favicon.ico** . The new URL didn't make sense to me, so as I previously mentioned, I switched back to StaticFilesConfig...

**Comment by provinzkraut** [comment]
> I checked again just now and realized there was one additional reason/inconsistency: after switching to create_static_files_router (using the exact same settings I had for StaticFilesConfig: directories=["static"], path="/static") I immediately noticed my favicon was 404ing all of a sudden because its URL was now **/schema/static/favicon.ico** instead of StaticFilesConfig's **/favicon.ico** . The new URL didn't make sense to me, so as I previously mentioned, I switched back to StaticFilesConfig...

That would be a bug in `StaticFilesConfig` though. If you set `directories=["static"], path="/static"`, all files from the `static` directory should be served under the `/static` path.

**Comment by Nozavi** [comment]
True, but I don't understand/want that "/schema" part/folder from create_static_files_router's URL

**Comment by provinzkraut** [comment]
Can you provide an MCVE for this?
