### ISSUE TITLE
NameError when `litestar.types.Guard` is used in the function parameter

### ISSUE THREAD

**Issue by Alc-Alc** [litestar-org/litestar#3421]
### Description

The example below raises a `NameError`. Ignoring the practicality of this code, I would expect this to at least start the app (maybe fail in OpenAPI).

For more context, this example is an attempt to single out "issue 2" in https://github.com/JacobCoffee/litestar-ldap/pull/1#issuecomment-2068201085. The issue mentioned by @JacobCoffee  raises a different `NameError` but I believe that and the example below are of same nature.

PS: This issue can be fixed if I do `from litestar.handlers.base import BaseRouteHandler` at some point before the app creation. However, I find this "wrong" because
1. Import without usage suggests it's for a side effect.
2. Note that I am not even adding it in `signature_namespace`

### MCVE

```python
from litestar.types import Guard
from litestar import get, Litestar
from typing import List, Optional

@get()
async def something(guards: Optional[List[Guard]] = None) -> int:
    return 1

app = Litestar([something])
```

### Steps to reproduce

```bash
1. Save 'mcve.py'
2. 'python mcve.py'
4. See error
```

### Logs

```bash
NameError: name 'BaseRouteHandler' is not defined
```

### Litestar Version

7814d597afadb4793e6b947a5644e36dfbab22ba (main as of issue)

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3421">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3421/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3421/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
What is the use-case for supplying a list of guards to a handler?

**Comment by peterschutt** [comment]
Anything that you put into a handler signature has to be able to be parsed as a runtime type. This means that the type itself, and all types referenced by the type must be in module scope, or in `signature_types` or `signature_namespace`.

`Guard` is a type alias:

https://github.com/litestar-org/litestar/blob/7814d597afadb4793e6b947a5644e36dfbab22ba/litestar/types/callable_types.py#L36

It references `BaseRouteHandler` among other types.

The names that we automatically include in the signature namespace are defined here:

https://github.com/litestar-org/litestar/blob/7814d597afadb4793e6b947a5644e36dfbab22ba/litestar/utils/signature.py#L37-L47

Those names are combined with the content of the `typing` module, the names within the module of the handler itself, and any names explicitly added to the namespace by the user, here:

https://github.com/litestar-org/litestar/blob/7814d597afadb4793e6b947a5644e36dfbab22ba/litestar/utils/signature.py#L161-L166

So `Callable` is known because we automatically include the `typing` module namespace, `ASGIConnection` is known because we include the `litestar.connection` namespace, and `SyncOrAsyncUnion` is known because we automatically include the `litestar.types` namespace. We don't include the `litestar.handlers` namespace because we've never had a reason to support passing handlers, or things that reference them into handler function signatures.

This issue is pretty much the same as this:

```py
from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from litestar import post

if TYPE_CHECKING:
    from other_module import OtherThing

@dataclass
class Thing:
    other_thing: OtherThing

@post()
def handler(data: Thing) -> None: ...
```

This will fail for the same reason, the type of `Thing` is in the module namespace, but a type that it references is not in the module namespace and so runtime type resolution will fail.

We can't include every type in the library in the implicit signature namespace, so we include the ones that are types themselves, or types that are types of the reserved kwargs. So, unless there's a compelling reason that we should be using DI to inject guards and route handlers into handler signatures, then this is a non-issue.

Additionally, `guards: Annotated[Optional[List[Guard]], Dependency(skip_validation=True)]` will also work around this issue.
