### ISSUE TITLE
Enhancement: need a way to update csrf token if secret changed

### ISSUE THREAD

**Issue by trim21** [litestar-org/litestar#3683]
### Summary

currently CSRF is check with hmac, and if csrf secret changed, users with previous csrf token will always failed.

Need a way to reset csrf token.

example flow:

- `App(csrf_config=CSRFConfig(secret='secret 1'))` 
- user A get csrf token.
- developer change config to `App(csrf_config=CSRFConfig(secret='secret 2'))` 

-> then user A will never pass csrf check again, unless we change `cookie_name` of `CSRFConfig`

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3683">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3683/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3683/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This is working as intended. If you change the secret, this indicates that the previous secret is no longer valid, and as such, tokens generated with it should also no longer be valid. 

Since the CSRF cookie is not set with an expiry time, it will be set as a *session cookie* implicitly by the browser, meaning it will expire once the session does (i.e. your client closes the browser window). 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#expiresdate

It is standard practice to require refreshing the session / re-authenticate if secrets like this expire.

**Comment by trim21** [comment]
thanks, didn't notice it's a session cookies.
