### ISSUE TITLE
Enhancement: DTO typing

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#721]
**What's the feature you'd like to ask for.**
Currently, DTOs require a lot of `#type: ignore`s to make type checks pass.

Considering this example [from our docs](https://starlite-api.github.io/starlite/usage/11-data-transfer-objects/#dtoto_model_instance), it would have to be defined like this to pass type checks:

```python
from starlite import get
from sqlalchemy import Column, Float, Integer, String
from sqlalchemy.orm import declarative_base
from starlite import DTOFactory
from starlite.plugins.sql_alchemy import SQLAlchemyPlugin

dto_factory = DTOFactory(plugins=[SQLAlchemyPlugin()])

Base = declarative_base()

class Company(Base):
    id = Column(Integer, primary_key=True)
    name = Column(String)
    worth = Column(Float)

CompanyDTO = dto_factory("CompanyDTO", Company)

@get()
def create_company(data: CompanyDTO) -> Company:  # type: ignore[valid-type]
    company: Company: data.to_model_instance()  # type: ignore[attr-defined]
    return company
```

Especially not having the DTO-instance methods visible to mypy is quite inconvenient. They are though visible to the type-checkers used in jetbrain's IDEs, and checks pass with pyright, so it's generally possible to infer these values.

Ideally, we could support this without a plugin. Maybe we can take inspiration from SQLAlchemy's move away from its mypy-plugin in 2.0 here.

**Comment by Goldziher** [comment]
we can try to use a metaclass for this, which can inject typing data. im not sure mypy will be able to handle this though.

**Comment by peterschutt** [comment]
I've got this going pretty nicely in starlite-saqlalchemy with `__class_getitem__`.

Here's an example:

```python
from __future__ import annotations

from datetime import date, datetime
from typing import Annotated

from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from starlite_saqlalchemy import dto


class Base(DeclarativeBase):
    id: Mapped[int] = mapped_column(primary_key=True)
    created: Mapped[datetime]
    updated: Mapped[datetime]


class Author(Base):
    __tablename__ = "authors"
    name: Mapped[str]
    dob: Mapped[date]

WriteDTO = dto.FromMapped[Annotated[Author, "write"]]
```
There's some different stuff going on there with the `"write"` that we don't have in starlite, but `dto.FromMapped` is a subclass of `pydantic.BaseModel` and defined `__class_getitem__()` which builds a new pydantic model that has all of the dto fields on it and returns that.

Type checkers have no dramas with it as it is just a type alias as far as they are concerned, and IDE is aware of all of the pydantic methods that you want to be interacting with on DTO, such as `parse_obj()` etc.

**Comment by provinzkraut** [comment]
@peterschutt This looks nice! Do you think this could be easily integrated into our DTOs?

**Comment by peterschutt** [comment]
I'll take a look at it once back on deck - prob early next week. I'm sure we'd be able to something similar.

**Comment by Goldziher** [comment]
This cannot be improved at present, not until mypy support `__class_getitem__`, which is still an open issue there.

**Comment by peterschutt** [comment]
Interesting, I've had a bit of success with it.. or so I thought.

**Comment by Goldziher** [comment]
> Interesting, I've had a bit of success with it.. or so I thought.

Well, I'd be happy to discover I'm wrong 😉

**Comment by peterschutt** [comment]
I'll have to have a closer look then.. maybe something I thought was typing ok is getting typed as `Any`? Time will tell!

Happy holidays👍

**Comment by peterschutt** [comment]
> This cannot be improved at present, not until mypy support `__class_getitem__`, which is still an open issue there.

I assume this the issue you are referring to: https://github.com/python/mypy/issues/11501?

The reason that this works for us, is that we only rely on interfaces provided by the generic base class. For example:

```py
WriteDTO = dto.FromMapped[Annotated[Author, "write"]]
```
As far as mypy is concerned, `WriteDTO` is a narrowed type alias of `dto.FromMapped`, where `dto.FromMapped` is a pydantic class with an extra `to_mapped()` method on the interface, which converts the DTO into an instance of a sqlalchemy mapped class.

The type that is returned by `__class_getitem__()` is a subclass of `dto.FromMapped` that is generated with pydantic's `create_model()` and from the runtime/pydantic perspective it has all of the fields that represent/validate the model attributes, but from a static typing perspective, it doesn't.

So, it "works" because we only use DTO for data transfer - that is we only ever call `dto_instance.to_mapped()` or `DTOType.from_orm()` when dealing with the DTOs. If we were to try to access one of the `Author` attributes on the DTO instance, there would be typing errors, but IMO relying on access to the model attributes on the DTO instance is an anti-pattern. One should convert the DTO to the domain type first, and then manipulate.

We can do similar with `starlite.dto`, where the logic in `DTOFactory.__call__()` instead occurs in `DTO.__class_getitem__()`, e.g., `MyDTO = starlite.dto.DTO[SourceType]`. We wouldn't have the issue of using the dynamically generated classes as types, and mypy would be aware of `from_model_instance()` and `to_model_instance()`.

Here is a domain and controller module pulled from something that I'm working on at the moment - this all works without any `type: ignore`'s or changes to mypy configs:

```python
# domain/contests.py
"""Contest domain."""
from __future__ import annotations

from datetime import datetime
from typing import Annotated

from sqlalchemy.orm import Mapped, mapped_column
from starlite_saqlalchemy import db, dto, repository, service

from .enums import ContestState, pg_contest_state_enum


class Contest(db.orm.Base):
    """Contest domain object."""

    description: Mapped[str | None]
    """Name of the contest.

    Auto-generated if `None`.
    """
    starts_at: Mapped[datetime]
    """Expected start date/time of the contest."""
    sport_id: Mapped[int]
    """ID of related sport."""
    state: Mapped[ContestState] = mapped_column(pg_contest_state_enum)
    """E.g., abandoned, cancelled, etc."""


class Repository(repository.sqlalchemy.SQLAlchemyRepository[Contest]):
    """Contest repository."""

    model_type = Contest


class Service(service.RepositoryService[Contest]):
    """Contest service."""

    repository_type = Repository


ReadDTO = dto.FromMapped[Annotated[Contest, "read"]]
WriteDTO = dto.FromMapped[Annotated[Contest, "write"]]
```
Note in this module, the only interaction with the DTO types/instances is for conversion to/from our domain types.

```python
# app/controllers/contests.py
"""Controllers for contests domain."""
from __future__ import annotations

from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession
from starlite import Dependency, Provide, Router, delete, get, post, put
from starlite.status_codes import HTTP_200_OK
from starlite_saqlalchemy.repository.types import FilterTypes

from domain.contests import ReadDTO, Service, WriteDTO


def provides_service(db_session: AsyncSession) -> Service:
    """Contest service dependency provider."""
    return Service(session=db_session)


DETAIL_ROUTE = "/{contest_id:uuid}"


@get()
async def get_contests(
    service: Service, filters: list[FilterTypes] = Dependency(skip_validation=True)
) -> list[ReadDTO]:
    """A paginated list of all contests."""
    return [ReadDTO.from_orm(item) for item in await service.list(*filters)]


@post()
async def create_contest(data: WriteDTO, service: Service) -> ReadDTO:
    """Create a new contest."""
    return ReadDTO.from_orm(await service.create(data.to_mapped()))


@get(path=DETAIL_ROUTE)
async def get_contest(service: Service, contest_id: UUID) -> ReadDTO:
    """Individual contest's detail view."""
    return ReadDTO.from_orm(await service.get(contest_id))


@put(path=DETAIL_ROUTE)
async def update_contest(data: WriteDTO, service: Service, contest_id: UUID) -> ReadDTO:
    """Register, or update a contest."""
    return ReadDTO.from_orm(await service.update(contest_id, data.to_mapped()))


@delete(path=DETAIL_ROUTE, status_code=HTTP_200_OK)
async def delete_contest(service: Service, contest_id: UUID) -> ReadDTO:
    """Delete the contests and return its representation."""
    return ReadDTO.from_orm(await service.delete(contest_id))


def create_router() -> Router:
    """Create a router for the contest domain."""
    return Router(
        path="/contests",
        route_handlers=[get_contests, create_contest, get_contest, update_contest, delete_contest],
        dependencies={"service": Provide(provides_service)},
        tags=["Contests"],
    )
```

**Comment by peterschutt** [comment]
Add `include` to config object in addition to `exclude`. Only one of `exclude` or `include` should be able to be provided.
